<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH7gJYcL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH7gJYcL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH7gJYcL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH7gJYcL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH7gJYcL\App_KernelDevDebugContainer([
    'container.build_hash' => 'H7gJYcL',
    'container.build_id' => '02bee4aa',
    'container.build_time' => 1653655033,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH7gJYcL');
