<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXM6PbWb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXM6PbWb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXM6PbWb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXM6PbWb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXM6PbWb\App_KernelDevDebugContainer([
    'container.build_hash' => 'XM6PbWb',
    'container.build_id' => '0631173c',
    'container.build_time' => 1653756210,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXM6PbWb');
